#! /bin/bash
ARGCOUNT=3

if [ $# -lt ${ARGCOUNT} ];
then
    echo "usage: testPack [dir][packname][output file]([WINDOW])"
    exit
fi

DIR=$1
PACK=$2
echo "${PACK}"
OUT=$3

rm -i ${OUT}
OUTP=`cat outputs`
WIN=""
if [ $# -gt `echo "${ARGCOUNT}" | bc` ];
then
    echo "with: ${4}"
    WIN=$4
fi
`echo "name,err,absErr,midinote,pTag,pEst,confidence,salience" > "${OUT}"`

EXT=".ogg"
if [ ${PACK} == "IOWA" ];
then
    EXT=".aiff"
fi
if [ ${PACK} == "philharmonia" ];
then
    echo "chaning extention to: .mp3"
    EXT=".mp3"
fi

for file in ${DIR}/*${EXT}
do
    echo "File: ${file}"
        python2 pitchAnalysis.py "${file}" "${PACK}" "${OUT}" "${WIN}"
done
