#! /bin/bash
ARGCOUNT=3

if [ $# -lt ${ARGCOUNT} ];
then
    echo "usage: testPack [dir][packname][output file]([big err print th])"
    exit
fi

DIR=$1
PACK=$2
OUT=$3
OUTP="name,err,absErr,midinote,pTag,pEst,conf,salience"
errTH=""
if [ $# -gt `echo "${ARGCOUNT}" | bc` ];
then
    echo "with: ${4}"
    errTH=$4
fi
rm -i ${OUT}
`echo "${OUTP}" > "${OUT}"`
for jsonFile in ${DIR}/*.json
do
    echo "File: ${jsonFile}"
    if [ "${errTH}" == "" ];
    then
        python2 freesoundPitchAnalysis.py "${jsonFile}" "${PACK}" "${OUT}" "${OUTP}"
    else
        python2 freesoundPitchAnalysis.py "${jsonFile}" "${PACK}" "${OUT}" "${OUTP}" "${errTH}"
    fi
done
